### ISSUE TITLE
Bump to 1.0

### ISSUE THREAD

**Issue by sheerun** [js-cli/node-findup-sync#27]
Hey, I think it's would good idea to bump version to 1.0 to show this module is stable and enable proper semver versioning. According to semver any bump for < 1.0 can be a breaking change..

**Comment by tkellen** [comment]
I'm not opposed to this. What do you think @jonschlinkert?

**Comment by jonschlinkert** [comment]
since 0.4.0 was a major refactor, perhaps we should publish 0.4.0 on npm first and give users some time to report any bugs. then bump to 1.0 if we're not getting any indication of regressions?

**Comment by tkellen** [comment]
:+1:

**Comment by phated** [comment]
I agree with this, but let's wait until we bring 0.4.2 into liftoff to make sure everything is good (since that was a pretty major bug)

**Comment by sttk** [comment]
Before version up to 1.0, I have a few questions about 0.4.2. (Or did I mistake or misunderstand anything?)

(1) Why is `micromatch` version old? The 2.3.7 is used, though the latest version is 2.3.11.

(2) Is the option `nocase` effective for only file basename (on case-sensitive platform)?

```js
(test.js)
var findup = require('findup-sync');
console.log(findup('a/b.txt'));
console.log(findup('a/B.TXT', { nocase: true }));
console.log(findup('A/B.TXT', { nocase: true }));
```

```
(on linux)
$ node test.js
/home/sttk/findup/a/b.txt
/home/sttk/findup/a/b.txt
null
```

(3) Is this behavior for glob good?

```js
(test2.js)
var findup = require('findup-sync');
console.log(findup('a/*.txt'));
console.log(findup('*/b.txt'));
console.log(findup('*.txt', { cwd: 'a' }));

console.log(findup('a/[a-z].txt'));
console.log(findup('[a-z]/b.txt'));
console.log(findup('[a-z].txt', { cwd: 'a' }));
```

```
(on linux)
$ node test2.js
null
null
/home/sttk/findup/a/b.txt
null
null
/home/sttk/findup/a/b.txt
```

**Comment by jonschlinkert** [comment]
> Why is micromatch version old? The 2.3.7 is used, though the latest version is 2.3.11.

it's a patch, so 2.3.11 will still be used. but we can force-bump if needed

> Is the option nocase effective for only file basename (on case-sensitive platform)?

Well, I think there are a couple of different issues in your examples. One is case-sensitivity, the other is recursion. 

Regarding recursion, although we test for nested directories, the description of the project is "Find the first file matching a given pattern in the current directory or the nearest ancestor directory." This means current directory or "up", whereas your examples show recursing "down". I can think of a couple of easy ways to implement support for one or two directories "down" without having to use glob or adding heavy logic, but beyond that we'd probably want to consider using glob in cases where recursion is necessary. IMHO, we shouldn't do this, since implementors could instead pass a pattern to findup that would return a directory that can be used as the cwd with glob. 

For the case sensitivity, I'm not sure what the best solution is yet - because every option we can think of has huge drawbacks But I can describe what's happening so we can discuss (fwiw, this is not a "matching" issue, it's a cwd/recursion issue). . Consider the following filepath:

```
/aaa/bbB/ccc/Ddd/eEe/FFF.txt
```

If this was a real filepath, but the user passed a pattern like `eee/*.txt`, it would fail. So would `EEE/*.txt`. The problem with trying to implement an exhaustive solution to this issue is that, to find `FFF.txt`, we would need to search every permutation of the given directory, from the root (` /aaa`) up to the cwd. 

Just thinking out loud...

**Comment by sttk** [comment]
@jonschlinkert  Thank you for your answers.

>>Why is micromatch version old? ...

> it's a patch, so 2.3.11 will still be used. but we can force-bump if needed

I see. If it is intended it's not a problem. I don't need it especially.

>> Is the option nocase effective for only file basename ...

> Regarding recursion, although we test for nested directories, the description of the project is "Find the first file matching a given pattern in the current directory or the nearest ancestor directory." ...

Sorry, I overlooked the description of this project and I understand this module is for finding "up". This question was my misunderstanding.

> For the case sensitivity, I'm not sure what the best solution is yet ...

Certainly it is not a simple problem. But as far as `liftoff` and its applications are concerned, there would be no problem.

**Comment by jonschlinkert** [comment]
I'm not opposed to bumping this to 1.0 now if @phated and @tkellen are good with it.

**Comment by phated** [comment]
Going to see the results of the latest change. The bugs didn't show up in our tracker for a few months.

**Comment by jonschlinkert** [comment]
> The bugs didn't show up in our tracker for a few months.

no prob. must have been an extremely rare edge case to take that long to surface

**Comment by tkellen** [comment]
:+1: to waiting it out for a few months. We're definitely close though!

**Comment by phated** [comment]
Hey all, going through my inbox and found this.  Ready to bump it?

**Comment by jonschlinkert** [comment]
That's fine with me. But I never saw any of the bugs you're referring to before, so I'll leave it to you to decide.

**Comment by phated** [comment]
Done.  This project should probably be revisited (including dependency upgrades) in the future.
